// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU2kSFYj0GmhqNxZHK9AeYGBJN6P2QSRk',
    appId: '1:927898726225:web:cdb55d0bced3c405dc6d70',
    messagingSenderId: '927898726225',
    projectId: 'electro-74b52',
    authDomain: 'electro-74b52.firebaseapp.com',
    storageBucket: 'electro-74b52.appspot.com',
    measurementId: 'G-9D1LRM9WP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnoLicQvbt39vtwfPOuvgN2ulTooQLSMA',
    appId: '1:927898726225:android:1b12d8b4e95565fcdc6d70',
    messagingSenderId: '927898726225',
    projectId: 'electro-74b52',
    storageBucket: 'electro-74b52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGG_4732NRdeY00bQgjEsDU5dcMIq_VDE',
    appId: '1:927898726225:ios:fbb500de058c78e1dc6d70',
    messagingSenderId: '927898726225',
    projectId: 'electro-74b52',
    storageBucket: 'electro-74b52.appspot.com',
    iosBundleId: 'com.example.electroVote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGG_4732NRdeY00bQgjEsDU5dcMIq_VDE',
    appId: '1:927898726225:ios:fbb500de058c78e1dc6d70',
    messagingSenderId: '927898726225',
    projectId: 'electro-74b52',
    storageBucket: 'electro-74b52.appspot.com',
    iosBundleId: 'com.example.electroVote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU2kSFYj0GmhqNxZHK9AeYGBJN6P2QSRk',
    appId: '1:927898726225:web:2dd88253e63ea32fdc6d70',
    messagingSenderId: '927898726225',
    projectId: 'electro-74b52',
    authDomain: 'electro-74b52.firebaseapp.com',
    storageBucket: 'electro-74b52.appspot.com',
    measurementId: 'G-W0QC8H1JQ9',
  );
}
